/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import formulariosInternos.IFrmRegistros;
import formulariosInternos.IFrmReporte;
import objetos.Vehiculos;
import objetos.Peaje;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cymaniatico
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    String user;
    int idRole;
    
    
    public FrmPrincipal(String user, int idRole) {
        initComponents();
        this.user = user;
        this.idRole = idRole;
        
        if(this.idRole!=1){
            menuReporte.setEnabled(false);
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peajeDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout peajeDesktopLayout = new javax.swing.GroupLayout(peajeDesktop);
        peajeDesktop.setLayout(peajeDesktopLayout);
        peajeDesktopLayout.setHorizontalGroup(
            peajeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
        );
        peajeDesktopLayout.setVerticalGroup(
            peajeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        menuRegistrar.setText("Agregar Registro");
        menuRegistrar.addActionListener(this::menuRegistrarActionPerformed);
        jMenu1.add(menuRegistrar);

        menuLogout.setText("Cerrar Sesion");
        menuLogout.addActionListener(this::menuLogoutActionPerformed);
        jMenu1.add(menuLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administrar");

        menuReporte.setText("Ver reporte");
        menuReporte.addActionListener(this::menuReporteActionPerformed);
        jMenu2.add(menuReporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peajeDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peajeDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        // TODO add your handling code here:
        IFrmRegistros registro = new IFrmRegistros(this);
        peajeDesktop.add(registro);
        registro.show();
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void menuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteActionPerformed
        // TODO add your handling code here:
        IFrmReporte reporte = new IFrmReporte();
        peajeDesktop.add(reporte);
        reporte.show();
    }//GEN-LAST:event_menuReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal(null,0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuRegistrar;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JDesktopPane peajeDesktop;
    // End of variables declaration//GEN-END:variables
}
