/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import objetos.Vehiculos;
import objetos.Usuarios;
import objetos.Peaje;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cymaniatico
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    
    ArrayList<Usuarios> listaUsuarios;
    String user, pass;
    int idRole;
    boolean confirmUser=false;
    
    ArrayList<Vehiculos> listaVehiculos;
    ArrayList<Peaje> registros;
    
    public FrmLogin() {
        initComponents();
        listaVehiculos = new ArrayList();
        registros = new ArrayList();
        listaVehiculos.add(new Vehiculos("Carro", 12000));
        listaVehiculos.add(new Vehiculos("MiniVan", 25000));
        listaVehiculos.add(new Vehiculos("Bus", 48000));
        listaVehiculos.add(new Vehiculos("Camion", 79000));
        datosIniciales();
        
    }
    
    public FrmLogin(ArrayList<Vehiculos> listaVehiculos, ArrayList<Peaje> registros){
        initComponents();
        this.listaVehiculos = listaVehiculos;
        this.registros = registros;
        datosIniciales();
    }
    
    public void datosIniciales(){
        listaUsuarios = new ArrayList();
        listaUsuarios.add(new Usuarios("LGARCIA", "1234", 1));
        listaUsuarios.add(new Usuarios("SPEREZ", "1234", 2));
        txtUser.setText("");
        txtPass.setText("");
    }
    
    public void iniciarSesion(){
        if(!txtUser.getText().isEmpty() 
                && !String.valueOf(txtPass.getPassword()).isEmpty()){
            user = txtUser.getText().toUpperCase();
            pass = String.valueOf(txtPass.getPassword());
            for (Usuarios usr : listaUsuarios) {
                if(usr.getUser().equals(user) && usr.getPass().equals(pass)){
                    confirmUser = true;
                    idRole= usr.getIdRole();
                    break;
                }else{
                    confirmUser = false;
                    idRole=0;
                }
            }
            
            if(confirmUser){
               FrmPrincipal principal = new FrmPrincipal(user, idRole, listaVehiculos, registros);
                principal.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error de Usuario y/o pass");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        txtUser.setText("jTextField1");

        jLabel2.setText("Contraseña");

        txtPass.setText("jPasswordField1");

        btnLogin.setText("Iniciar Sesion");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin)
                    .addComponent(jLabel1))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        iniciarSesion();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
