/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formulariosInternos;

import formularios.FrmPrincipal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.InfoConexion;
import objetos.Peaje;

/**
 *
 * @author cymaniatico
 */
public class IFrmReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmReporte
     */
    
    ArrayList<Peaje> reg;
    InfoConexion conexion;
    
    public IFrmReporte() {
        initComponents();
        mostrarInfo();
    }
    
    
    public void mostrarInfo(){
        try(Connection con = DriverManager.getConnection(conexion.getUrl(), 
                conexion.getUsername(), conexion.getPassword())) {
            
            DefaultTableModel modelo = new DefaultTableModel();
            reg.clear();
            Statement stm = con.createStatement();
            String query = "call mostrarInfo()";
            ResultSet rs = stm.executeQuery(query);
            ResultSetMetaData rsmt = rs.getMetaData();
            
            for(int i = 1; i<= rsmt.getColumnCount(); i++){
                modelo.addColumn(rsmt.getColumnLabel(i));
            }
            
            while(rs.next()){
                String placa = rs.getString("Placa");
                String fecha = rs.getString("Fecha");
                String tipoVehiculo = rs.getString("Tipo de vehiculo");
                int valor = rs.getInt("Valor pagado");
                
                Object[] filas = new Object[rsmt.getColumnCount()];
                for(int i = 1; i<=rsmt.getColumnCount(); i++){
                    filas[i-1]= rs.getObject(1);
                }
                modelo.addRow(filas);
                
            }
            tableReporte.setModel(modelo);      
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableReporte = new javax.swing.JTable();

        tableReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableReporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReporte;
    // End of variables declaration//GEN-END:variables
}
